### ISSUE TITLE
Cursor shows insert bar instead of hand when hovering

### ISSUE THREAD

**Issue by nathanbunker** [Schmidt96u96/PI_XML_EDITOR#11]
When clicking on Forget Password and Sign Up the mouse is not switching to a hand to indicate that you can click. I have a selector which makes it seem like I can't click it. 

![image](https://user-images.githubusercontent.com/122847/73900248-635d6180-484c-11ea-8785-6f624d0bf3bf.png)

**Comment by FredericVenier** [comment]
Done, we now have a pointer when hovering links.
