### ISSUE TITLE
Page jumps around a lot

### ISSUE THREAD

**Issue by nathanbunker** [Schmidt96u96/PI_XML_EDITOR#14]
The column widths change depending on the content which causes the page to "jump" a lot, very stressing on the ideas. Would it be possible to fix the "Edit Data" page so that it is the same width of the page and the three columns all take up a specific width of the page. The first column might take up 30%, the codes 30% and the Details 40%. Then it won't change each time you click, search or edit.

**Comment by FredericVenier** [comment]
The column widths doesn't change depending on the content anymore.
