### ISSUE TITLE
Differences between XML uploaded and downloaded

### ISSUE THREAD

**Issue by nathanbunker** [Schmidt96u96/PI_XML_EDITOR#17]
There are differences between the XML uploaded from what is downloaded. The downloaded XML needs to be changed in the following ways:

- Indented 4 spaces for every indention (currently indents 2 spaces)

- There are no quotes around codeset name

![image](https://user-images.githubusercontent.com/122847/73901291-948b6100-484f-11ea-85a0-944f7eca39f5.png)

- The use-date tags are ordered as such: <not-before> <not-expected-before> <not-expected-after> <not-after>

![image](https://user-images.githubusercontent.com/122847/73901357-c6042c80-484f-11ea-81d5-70d924649e9e.png)

There might be more issues. Please fix these issues and test on your end but uploading the Vaccination CVX Code.xml, uploading it then downloading and comparing them together. They should match byte for byte. 

This is a very critical issue because we need the file to look the same except for the changes made so that we can track the changes without the noise of other non-essential changes to the XML.

**Comment by BaptouKrafft** [comment]
I think it's done
