### ISSUE TITLE
Only admins should be able to add a code set

### ISSUE THREAD

**Issue by nathanbunker** [Schmidt96u96/PI_XML_EDITOR#19]
A regular user who can edit codesets should not have the ability a code set by uploading a file or on the Edit Data page under Sets:

![image](https://user-images.githubusercontent.com/122847/73901715-dcf74e80-4850-11ea-9ccc-0d9c5f3eb9a1.png)

**Comment by FredericVenier** [comment]
Fixed, only admin can add a new set and have access to the 'add file' page.
