### ISSUE TITLE
Please put software version

### ISSUE THREAD

**Issue by nathanbunker** [Schmidt96u96/PI_XML_EDITOR#3]
There needs to be a software version visible on the front page. Should follow this format:

1.2.3

1 is the major release version, we are at version
2 is the release version, you can start anywhere you like
3 is the patch version, only for minor fixes, no new functionality or incompatible changes

**Comment by nathanbunker** [comment]
I didn't see this in the application I checked down, I'll test this tomorrow when you release the next version and see if it gets committed then.

**Comment by FredericVenier** [comment]
The version is displayed when clicking the learn more button on the home view.
