### ISSUE TITLE
Search Option for coded values

### ISSUE THREAD

**Issue by nathanbunker** [Schmidt96u96/PI_XML_EDITOR#5]
Create a filter/search option that allows the user to type in part of the id or label they want to filter by. If one or more characters are in the filter box, only show the id and label for values that have this string fragment in either the id or label. This will help the user to cut the list down so it's not so long.

**Comment by FredericVenier** [comment]
Search option added on the edit view. It looks for id or values containing the string.

**Comment by nathanbunker** [comment]
Search option looks great. This will allow us to work with a longer list.
