### ISSUE TITLE
Menu - Labels and Order

### ISSUE THREAD

**Issue by nathanbunker** [Schmidt96u96/PI_XML_EDITOR#6]
Here are changes to make to the text of the menus:

- Home: Home
- Feed: Changes
- Edit Data: Codes
- Add File: Upload
- User Settings: Settings
- Admin: Admin
- Log out: Log Out

Please also re-order the menu items:
- Home
- Codes
- Changes
- Settings
- Admin
- Upload
- Log Out

**Comment by FredericVenier** [comment]
Done.
