### ISSUE TITLE
Put name of application in email

### ISSUE THREAD

**Issue by nathanbunker** [Schmidt96u96/PI_XML_EDITOR#9]
Can you put the name of the application in the email. It should say "Verify your email for the MQE Knowledge Base"

![image](https://user-images.githubusercontent.com/122847/73900079-d4e8e000-484b-11ea-98f1-04224464634e.png)

**Comment by FredericVenier** [comment]
The project has been renamed on firebase to MQE Knowledge Base instead of project-40418...
